DATA:
  DATA_NAME: 'THUMOS'
  DATA_ROOT: 'data/pku_mmd'
  TRAIN_SESSION_SET: 'split_train'
  TEST_SESSION_SET: 'split_test'


INPUT:
  MODALITY: 'visual'
  VISUAL_FEATURE: 'features'
  TARGET_PERFRAME: 'targets'

MODEL:
  MODEL_NAME: 'LSTR'
  FEATURE_HEAD:
    LINEAR_ENABLED: True
    LINEAR_OUT_FEATURES: 1024
  LSTR:
    NUM_HEADS: 16
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.2
    ACTIVATION: 'relu'
    LONG_MEMORY_SECONDS: 128
    LONG_MEMORY_SAMPLE_RATE: 4
    WORK_MEMORY_SECONDS: 8
    WORK_MEMORY_SAMPLE_RATE: 1
    ENC_MODULE: [
      [16, 1, True], [32, 2, True]
    ]
    DEC_MODULE: [-1, 2, True]
  CRITERIONS: [['MCE', {}]]
DATA_LOADER:
  BATCH_SIZE: 16
  NUM_WORKERS: 0
  PIN_MEMORY: False

SOLVER:
  NUM_EPOCHS: 10
  OPTIMIZER: 'adam'
  BASE_LR: 7e-05
  WEIGHT_DECAY: 5e-05
  SCHEDULER:
    SCHEDULER_NAME: 'warmup_cosine'
    WARMUP_FACTOR: 0.3
    WARMUP_EPOCHS: 10.0
    WARMUP_METHOD: 'linear'
